// Particle Configuration Constants
export const PARTICLE_CONFIG = {
  sparkle: {
    velocity: { x: 8, y: 8 },
    life: { min: 30, max: 20 },
    size: { min: 2, max: 3 },
    color: "#ffff00",
    shadowBlur: 8,
    shape: "circle",
    effects: ["cross_lines"],
  },
  explosion: {
    velocity: { x: 12, y: 12 },
    life: { min: 40, max: 30 },
    size: { min: 3, max: 4 },
    color: "#ff6b6b",
    shadowBlur: 6,
    shape: "circle",
  },
  magic: {
    velocity: { x: 6, y: 6 },
    life: { min: 50, max: 40 },
    size: { min: 1, max: 2 },
    color: "#00ffff",
    shadowBlur: 4,
    shape: "diamond",
  },
  wall_hit: {
    velocity: { x: 10, y: 10 },
    life: { min: 25, max: 15 },
    size: { min: 1, max: 2 },
    color: "#00ff00",
    shadowBlur: 3,
    shape: "square",
  },
  paddle_hit: {
    velocity: { x: 15, y: 15 },
    life: { min: 20, max: 10 },
    size: { min: 2, max: 3 },
    color: "#00ff00",
    shadowBlur: 5,
    shape: "star",
  },
  score: {
    velocity: { x: 20, y: 20 },
    life: { min: 35, max: 25 },
    size: { min: 3, max: 4 },
    color: "#ff00ff",
    shadowBlur: 8,
    shape: "plus",
  },
  shield_reflection: {
    velocity: { x: 12, y: 12 },
    life: { min: 30, max: 20 },
    size: { min: 2, max: 3 },
    color: "#0096ff",
    shadowBlur: 6,
    shape: "diamond",
    effects: ["cross_lines"],
  },
};
